steps:
  # Step 1: Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/my-streamlit-app',
      '.'
    ]

  # Step 2: Push image to Google Container/Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/my-streamlit-app'
    ]

  # Step 3: Deploy to Cloud Run (public URL)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'my-streamlit-app',
      '--image', 'gcr.io/$PROJECT_ID/my-streamlit-app',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--service-account=streamlit-exec@$PROJECT_ID.iam.gserviceaccount.com'
    ]

# The image built by this pipeline
images:
  - 'gcr.io/$PROJECT_ID/my-streamlit-app'

# Cloud Logging only (no Cloud Monitoring)
options:
  logging: CLOUD_LOGGING_ONLY
