steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${REGISTRY_URL}/billing-app/my-streamlit-app:$COMMIT_SHA',
      '.'
    ]

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${REGISTRY_URL}/billing-app/my-streamlit-app:$COMMIT_SHA'
    ]

images:
  - 'gcr.io/$PROJECT_ID/my-streamlit-app'
    
options:
  logging: CLOUD_LOGGING_ONLY
